export const UPDATE_USER_SETTING = 'UPDATE_USER_SETTING';
export const USER_INFO_UPDATE = 'USER_INFO_UPDATE';
export const USER_PROFILE_START_EDIT = 'USER_PROFILE_START_EDIT';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_PROFILE_FINISH_EDIT = 'USER_PROFILE_FINISH_EDIT';
export const USER_ADD_CONNECTION = 'USER_ADD_CONNECTION';
export const USER_SET_SUGGESTION_USERNAME = 'USER_SET_SUGGESTION_USERNAME';
export const USER_ACCOUNT_INFO_UPDATE = 'USER_ACCOUNT_INFO_UPDATE';

export const VALIDATION_USER_USERNAME_SUCCESS = 'VALIDATION_USER_USERNAME_SUCCESS';
export const VALIDATION_USER_USERNAME_FAILED = 'VALIDATION_USER_USERNAME_FAILED';
export const VALIDATION_CLEAR_ALL = 'VALIDATION_CLEAR_ALL';

export const REQUESTING = 'REQUESTING';
export const REQUEST_FINISHED = 'REQUEST_FINISHED';

/*
 * ANSWER
 */
export const ANSWER_SHOW_INPUT_BOARD = 'ANSWER_SHOW_INPUT_BOARD';
export const ANSWER_CLOSE_INPUT_BOARD = 'ANSWER_CLOSE_INPUT_BOARD';
export const ANSWER_SUCCESS = 'ANSWER_SUCCESS';
export const ANSWER_FAILED = 'ANSWER_FAILED';
export const ANSWER_CLEAR_RESULT = 'ANSWER_CLEAR_RESULT';
export const ANSWER_SHARE_START = 'ANSWER_SHARE_START';
export const ANSWER_SHARE_FINISH = 'ANSWER_SHARE_FINISH';
export const ANSWER_SHOW_SHARE_DIALOG = 'ANSWER_SHOW_SHARE_DIALOG';
export const ANSWER_HIDE_SHARE_DIALOG = 'ANSWER_HIDE_SHARE_DIALOG';
export const ANSWER_START = 'ANSWER_START';
export const ANSWER_FINISH = 'ANSWER_FINISH';
export const ANSWER_PRIVATE_SEND = 'ANSWER_PRIVATE_SEND';
export const ANSWER_SENDING = 'ANSWER_SENDING';

/*
 * ASKING ACTIONS
 */
export const ASKING_SHOW_INPUT_BOARD = 'ASKING_SHOW_INPUT_BOARD';
export const ASKING_HIDE_INPUT_BOARD = 'ASKING_HIDE_INPUT_BOARD';
export const ASKING_REQUESTING = 'ASKING_REQUESTING';
export const ASKING_FINISHED = 'ASKING_FINISHED';
export const ASKING_SET_INFO = 'ASKING_SET_INFO';

/*
 * QUESTIONS ACTIONS
 */
export const QUESTIONS_SHOW_ITEM_MENU = 'QUESTIONS_SHOW_ITEM_MENU';
export const QUESTIONS_CLOSE_ITEM_MENU = 'QUESTIONS_CLOSE_ITEM_MENU';
export const QUESTIONS_PUBLIC_UPDATE = 'QUESTIONS_PUBLIC_UPDATE';
export const QUESTIONS_SET_ANSWERED = 'QUESTIONS_SET_ANSWERED';
export const QUESTIONS_UPDATE = 'QUESTIONS_UPDATE';
export const QUESTION_DELETE = 'QUESTION_DELETE';
export const QUESTIONS_SHOW = 'QUESTIONS_SHOW';
export const QUESTIONS_CLOSE = 'QUESTIONS_CLOSE';
export const QUESTIONS_SENT_UPDATE = 'QUESTIONS_SENT_UPDATE';
export const QUESTIONS_CLEAR = 'QUESTIONS_CLEAR';
export const QUESTIONS_SENT_CLEAR = 'QUESTIONS_SENT_CLEAR';
export const QUESTIONS_UNANSWERED_COUNT_UPDATE = 'QUESTIONS_UNANSWERED_COUNT_UPDATE';
export const QUESTIONS_SWITCH_TAB = 'QUESTIONS_SWITCH_TAB';
export const QUESTIONS_UPDATING = 'QUESTIONS_UPDATING';

/*
 * APP ACTIONS
 */
export const APP_GLOBAL_RESULT_SHOW = 'APP_GLOBAL_RESULT_SHOW';
export const APP_GLOBAL_RESULT_HIDE = 'APP_GLOBAL_RESULT_HIDE';
export const APP_DATA_INITIATED = 'APP_DATA_INITIATED';
export const APP_PAGES_TERMS_TOGGLE = 'APP_PAGES_TERMS_TOGGLE';
export const APP_PAGES_LANGUAGES_TOGGLE = 'APP_PAGES_LANGUAGES_TOGGLE';
export const APP_LOADING = 'APP_LOADING';
export const APP_SHOW_EUGDPR = 'APP_SHOW_EUGDPR';
export const APP_HIDE_EUGDPR = 'APP_HIDE_EUGDPR';
export const SAVE_IMAGE = 'SAVE_IMAGE';
export const SAVE_IMAGE_SUCCESS = 'SAVE_IMAGE_SUCCESS';
export const CLEAR_SAVE_IMAGE = 'CLEAR_SAVE_IMAGE';

/*
 * CUSTOM SHARE ACTIONS
 */
export const CUSTOM_SHARE_SHOW = 'CUSTOM_SHARE_SHOW';
export const CUSTOM_SHARE_HIDE = 'CUSTOM_SHARE_HIDE';
export const CUSTOM_SHARE_START = 'CUSTOM_SHARE_START';
export const CUSTOM_SHARE_FINISH = 'CUSTOM_SHARE_FINISH';

/*
 * AUTHENTICATION
 */
export const AUTHENTICATION_REQUESTING_FACEBOOK = 'AUTHENTICATION_REQUESTING_FACEBOOK';
export const AUTHENTICATION_REQUESTING = 'AUTHENTICATION_REQUESTING';
export const AUTHENTICATION_REQUESTED = 'AUTHENTICATION_REQUESTED';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_METHODS_SHOW = 'AUTHENTICATION_METHODS_SHOW';
export const AUTHENTICATION_METHODS_HIDE = 'AUTHENTICATION_METHODS_HIDE';

/*
 * PROFILE
 */
export const PROFILE_FETCHED_SUCCESS = 'PROFILE_FETCHED_SUCCESS';
export const PROFILE_FETCH_FAILED = 'PROFILE_FETCH_FAILED';
export const PROFILE_FETCHING = 'PROFILE_FETCHING';
export const PROFILE_FOLLOW_CHECKED = 'PROFILE_FOLLOW_CHECKED';

/*
 * FOLLOW
 */
export const FOLLOW_STATUS_UPDATED = 'FOLLOW_STATUS_UPDATED';
export const FOLLOW_FETCHED_SUCCESS = 'FOLLOW_FETCHED_SUCCESS';
export const FOLLOW_FETCH_FAILED = 'FOLLOW_FETCH_FAILED';
export const FOLLOW_FETCHING = 'FOLLOW_FETCHING';
export const FOLLOW_HANDLER_STATUS_SUCCESS = 'FOLLOW_HANDLER_STATUS_SUCCESS';
export const FOLLOW_HANDLER_STATUS_FAILED = 'FOLLOW_HANDLER_STATUS_FAILED';

/*
 * CONNECTED USER
 */
export const CONNECTED_USERS_UPDATE = 'CONNECTED_USERS_UPDATE';

/**
 * ALERTS
 * @type {string}
 */
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_CLEAR = 'ALERT_CLEAR';

/**
 * APP
 * @type {string}
 */
export const APP_SET_LOCALE = 'APP_SET_LOCALE';
export const APP_SET_LANGUAGE_CODE = 'APP_SET_LANGUAGE_CODE';
export const APP_SET_PLATFORM = 'APP_SET_PLATFORM';
export const APP_NAVIGATION_CHANGE = 'APP_NAVIGATION_CHANGE';
export const APP_MASK_SHOW = 'APP_MASK_SHOW';
export const APP_MASK_CLOSE = 'APP_MASK_CLOSE';
export const APP_CUSTOM_ALERT_TIMEOUT = 'APP_CUSTOM_ALERT_TIMEOUT';

/**
 * Confirm
 * @type {string}
 */
export const CONFIRM_DISMISS = 'CONFIRM_DISMISS';
export const CONFIRM_SHOW = 'CONFIRM_SHOW';

/*
 * Friends
 */
export const FRIENDS_COUNT = 'FRIENDS_COUNT';
