const Resources = {
  defaultAvatar: require('../assets/images/askme/default-avatar.png'),
  blockedIcon: require('../assets/images/askme/app/blocked.png'),
  settingIcon: require('../assets/images/askme/app/setting-icon.svg'),
  backWhiteIcon: require('../assets/images/askme/app/back-white-icon.svg'),
  emptyStateDashboard: require('../assets/images/askme/app/empty-state-dashboard.svg'),
  unFollowIcon: require('../assets/images/askme/app/unfollow.svg'),
  followIcon: require('../assets/images/askme/app/follow.svg'),
  tickIcon: require('../assets/images/askme/app/tick.svg'),
  tickBoldIcon: require('../assets/images/askme/app/tick-bold.svg'),
  crossIcon: require('../assets/images/askme/app/cross.svg'),
  crossBoldIcon: require('../assets/images/askme/app/cross-bold.svg'),
  blueLogo: require('../assets/images/askme/app/logo-blue.svg'),
  closeIcon: require('../assets/images/askme/app/close-icon.svg'),
  spinIcon: require('../assets/images/askme/spin.svg'),
  // loaderIcon: require('../assets/images/loader.gif'),
  backIcon: require('../assets/images/askme/app/back-icon.svg'),
  refreshIcon: require('../assets/images/askme/refresh.svg'),
  questionIcon: require('../assets/images/askme/question.svg'),
  // homeIcon: require('../assets/images/chess-ui/v1.0/home.svg'),
  notFoundEmptyState: require('../assets/images/askme/app/empty-state-404.svg'),
  oopsPageEmptyState: require('../assets/images/askme/app/oops-page.svg'),
  welcomePageEmptyState: require('../assets/images/askme/app/welcome-page.svg'),
  facebookWhiteIcon: require('../assets/images/askme/app/facebook-icon-white.svg'),
  replyIcon: require('../assets/images/askme/app/reply-icon.svg'),
  wallEmptyState: require('../assets/images/askme/app/empty-state-wall.svg'),
  friendsEmptyState: require('../assets/images/askme/app/empty-state-friends.svg'),
  newRepliesEmptyState: require('../assets/images/askme/app/empty-state-new-replies.svg'),
  questionsEmptyState: require('../assets/images/askme/app/empty-state-questions.svg'),
  facebookIcon: require('../assets/images/askme/app/facebook-icon.svg'),
  copyIcon: require('../assets/images/askme/app/copy.svg'),
  messageMenu: require('../assets/images/askme/awesome-svgs/ellipsis-h-grey.svg'),
  shareLink: require('../assets/images/askme/awesome-svgs/share-alt-white.svg'),
  blockPerson: require('../assets/images/askme/awesome-svgs/ban-solid-white.svg'),
  trash: require('../assets/images/askme/awesome-svgs/trash-white.svg'),
  flag: require('../assets/images/askme/awesome-svgs/flag-white.svg'),
  close: require('../assets/images/askme/awesome-svgs/close-white.svg'),
  edit: require('../assets/images/askme/awesome-svgs/edit-white.svg'),
  detail: require('../assets/images/askme/awesome-svgs/ellipsis-v-grey.svg'),
  inviteFriend: require('../assets/images/askme/awesome-svgs/chevron-right-grey.svg'),
  dropDown: require('../assets/images/askme/awesome-svgs/angle-down-black.svg'),
  languageSelector: require('../assets/images/askme/awesome-svgs/angle-down-white.svg'),
  submitDone: require('../assets/images/askme/awesome-svgs/check-white.svg'),
  unblockPerson: require('../assets/images/askme/awesome-svgs/check-square-white.svg'),
  telegramPlane: require('../assets/images/askme/awesome-svgs/telegram-plane-white.svg'),
  alertError: require('../assets/images/askme/awesome-svgs/exclamation-circle-solid-red.svg'),
  next: require('../assets/images/askme/awesome-svgs/arrow-right-grey.svg'),
  previous: require('../assets/images/askme/awesome-svgs/arrow-left-grey.svg'),
  globalLoader: require('../assets/images/askme/app/global-game-loader.gif'),
  sequence: require('../assets/images/askme/awesome-svgs/sequence-icon.jpg'),
  love_homepage: require('../assets/images/askme/app/love_homepage.svg'),
  dash_arrow_homepage: require('../assets/images/askme/app/dash_arrow_homepage.svg'),
  send: require('../assets/images/askme/awesome-svgs/send.svg')
};

export default Resources;
